INSERT INTO Scontrino(fk_sede_via, fk_sede_civico, fk_sede_cap, prezzo_totale) VALUES ('Via Mar Rosso', '5', 24123, 0.90);
INSERT INTO Scontrino(fk_sede_via, fk_sede_civico, fk_sede_cap, prezzo_totale) VALUES ('Viale Manzoni', '53', 80121, 0.90); 
INSERT INTO Scontrino(fk_sede_via, fk_sede_civico, fk_sede_cap, prezzo_totale) VALUES ('Viale delle industrie', '22', 80142, 6); 
INSERT INTO Scontrino(fk_sede_via, fk_sede_civico, fk_sede_cap, prezzo_totale) VALUES ('Viale Manzoni', '53', 80121, 3.99); 
INSERT INTO Scontrino(fk_sede_via, fk_sede_civico, fk_sede_cap, prezzo_totale) VALUES ('Via Massimo', '76', 61126, 1.20); 
INSERT INTO Scontrino(fk_sede_via, fk_sede_civico, fk_sede_cap, prezzo_totale) VALUES ('Via Massimo', '76', 61126, 3.29); 
INSERT INTO Scontrino(fk_sede_via, fk_sede_civico, fk_sede_cap, prezzo_totale) VALUES ('Via Rosa', '4', 24122, 2.50); 
INSERT INTO Scontrino(fk_sede_via, fk_sede_civico, fk_sede_cap, prezzo_totale) VALUES ('Piazza Verdi', '50', 29132, 5.50);
INSERT INTO Scontrino(fk_sede_via, fk_sede_civico, fk_sede_cap, prezzo_totale) VALUES ('Viale delle industrie', '22', 80142, 1.50); 
INSERT INTO Scontrino(fk_sede_via, fk_sede_civico, fk_sede_cap, prezzo_totale) VALUES ('Via Napoli', '3', 24126, 1.50); 
INSERT INTO Scontrino(fk_sede_via, fk_sede_civico, fk_sede_cap, prezzo_totale) VALUES ('Via Napoli', '3', 24126, 1.00); 
INSERT INTO Scontrino(fk_sede_via, fk_sede_civico, fk_sede_cap, prezzo_totale) VALUES ('Via Massimo', '76', 61126, 2.0); 
