INSERT INTO Esercizio VALUES ('Tapis roulant', 'Cardio');
INSERT INTO Esercizio VALUES ('Spinte chest press', 'Pettorali');
INSERT INTO Esercizio VALUES ('Spinte shoulder press', 'Spalle');
INSERT INTO Esercizio VALUES ('Pectoral Machine', 'Pettorali');
INSERT INTO Esercizio VALUES ('Tirate cavi basso', 'Tricipiti');
INSERT INTO Esercizio VALUES ('French press su panca', 'Tricipiti');
INSERT INTO Esercizio VALUES ('Abdominal Machine', 'Addome');
INSERT INTO Esercizio VALUES ('Alzate su panca reclinata', 'Addome');
INSERT INTO Esercizio VALUES ('Leg extension', 'Quadricipiti');
INSERT INTO Esercizio VALUES ('Leg curl seduto', 'Femorali');
INSERT INTO Esercizio VALUES ('Slanci gamba con multi hip', 'Glutei');
INSERT INTO Esercizio VALUES ('Arnold press', 'Spalle');
INSERT INTO Esercizio VALUES ('Alzate laterali', 'Spalle');
INSERT INTO Esercizio VALUES ('Alzate frontali', 'Spalle');
INSERT INTO Esercizio VALUES ('Pulley', 'Dorsali');
INSERT INTO Esercizio VALUES ('Lat machine avanti', 'Dorsali');
INSERT INTO Esercizio VALUES ('Vertical Row', 'Dorsali');
INSERT INTO Esercizio VALUES ('Curl hammer con cavi', 'Bicipiti');
INSERT INTO Esercizio VALUES ('Curl in piedi con due manubri', 'Bicipiti');
INSERT INTO Esercizio VALUES ('Curl in piedi con bilanciere', 'Bicipiti');
INSERT INTO Esercizio VALUES ('Curl con un manubrio su panca scott', 'Bicipiti');
INSERT INTO Esercizio VALUES ('Leg press', 'Quadricipiti');
INSERT INTO Esercizio VALUES ('Stacchi a gambe tese con bilanciere', 'Femorali');
INSERT INTO Esercizio VALUES ('Squat', 'Quadricipiti');
INSERT INTO Esercizio VALUES ('Sumo squat', 'Quadricipiti');
