INSERT INTO Lezione_corso(fk_sala_codice, fk_sala_via, fk_sala_civico, fk_sala_cap, fk_corso, fk_dipendente, giorno_settimana_lezione, ora_inizio, ora_fine) VALUES('D1', 'Viale Manzoni', '53', 80121, 'Karate', 'CG36854JK', 'FRI', 14.00, 15.00);
INSERT INTO Lezione_corso(fk_sala_codice, fk_sala_via, fk_sala_civico, fk_sala_cap, fk_corso, fk_dipendente, giorno_settimana_lezione, ora_inizio, ora_fine) VALUES('B1', 'Via Giuseppe Verdi', '1', 80121, 'Yoga', 'CU36584LB', 'MON', 9.00, 10.00);
INSERT INTO Lezione_corso(fk_sala_codice, fk_sala_via, fk_sala_civico, fk_sala_cap, fk_corso, fk_dipendente, giorno_settimana_lezione, ora_inizio, ora_fine) VALUES('C2', 'Piazza Garibaldi', '33', 80136, 'Zumba', 'CF36945GV', 'TUE', 18.00, 19.00);
INSERT INTO Lezione_corso(fk_sala_codice, fk_sala_via, fk_sala_civico, fk_sala_cap, fk_corso, fk_dipendente, giorno_settimana_lezione, ora_inizio, ora_fine) VALUES('B3', 'Via Giuseppe Verdi', '1', 80121, 'Aerobica', 'CO11025RE', 'WED', 19.00, 20.00);
INSERT INTO Lezione_corso(fk_sala_codice, fk_sala_via, fk_sala_civico, fk_sala_cap, fk_corso, fk_dipendente, giorno_settimana_lezione, ora_inizio, ora_fine) VALUES('B3', 'Via Giuseppe Verdi', '1', 80121, 'Spinning', 'CO11025RE', 'WED', 20.00, 21.00);
INSERT INTO Lezione_corso(fk_sala_codice, fk_sala_via, fk_sala_civico, fk_sala_cap, fk_corso, fk_dipendente, giorno_settimana_lezione, ora_inizio, ora_fine) VALUES('C3', 'Piazza Garibaldi', '33', 80136, 'Step', 'CF36945GV', 'THU', 14.00, 15.00);
INSERT INTO Lezione_corso(fk_sala_codice, fk_sala_via, fk_sala_civico, fk_sala_cap, fk_corso, fk_dipendente, giorno_settimana_lezione, ora_inizio, ora_fine) VALUES('B3', 'Via Giuseppe Verdi', '1', 80121, 'Aerobica', 'CO11025RE', 'WED', 20.00, 21.00);
INSERT INTO Lezione_corso(fk_sala_codice, fk_sala_via, fk_sala_civico, fk_sala_cap, fk_corso, fk_dipendente, giorno_settimana_lezione, ora_inizio, ora_fine) VALUES('D1', 'Viale Manzoni', '53', 80121, 'Pump', 'CG36854JK', 'FRI', 16.00, 17.00);

